services:
  db:
    container_name: postgres
    image: postgres:17.4
    env_file:
      - .env
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      PGDATABASE: ${POSTGRES_DB}
    volumes: 
      - db:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge

volumes:
  db:


